import type { Metadata } from "next";

import { isIndexable, siteConfig, type SiteRoute } from "@/lib/site";

type OgImage = { url: string; width: number; height: number; alt: string };

// Browser tab titles are pipe delimited and never use colons. The home page
// reads "<AppName> | <Tagline>"; every other page reads "<PageName> | <AppName>".
export const TITLE_SEPARATOR = " | ";

/**
 * Joins title parts with TITLE_SEPARATOR, most specific part first.
 *
 * Throws on a part that contains a colon or a pipe, so a title that breaks the
 * format fails the build (or the request, for dynamic routes) instead of
 * reaching the tab. Clean titles that come from data before passing them in.
 */
export function pageTitle(...parts: string[]) {
  for (const part of parts) {
    if (/[:|]/.test(part)) {
      throw new Error(
        `Page title part "${part}" contains a colon or a pipe. Titles are pipe delimited ("<PageName> | <AppName>"); rephrase it or split it into separate parts.`,
      );
    }
  }
  return parts.join(TITLE_SEPARATOR);
}

export const DEFAULT_TITLE = pageTitle(siteConfig.name, siteConfig.tagline);

export const OG_IMAGE_SIZE = { width: 1200, height: 630 };
export const OG_IMAGE_ALT = `${siteConfig.name}: ${siteConfig.tagline}`;

// The card generated by src/app/opengraph-image.tsx. Next.js only attaches a
// file-based image to the segment that holds the file, and a page that sets
// its own openGraph replaces it, so pages reference the default explicitly.
const DEFAULT_OG_IMAGE: OgImage = {
  url: "/opengraph-image",
  ...OG_IMAGE_SIZE,
  alt: OG_IMAGE_ALT,
};

type PageMetadataOptions = Pick<SiteRoute, "path" | "title" | "description"> & {
  index?: boolean;
  // Open Graph object type. Use "article" for posts and docs.
  type?: "website" | "article";
  // Social card for the page. Defaults to the site card. Pass "file" when the
  // route has its own opengraph-image file next to its page, so that file is
  // used instead.
  image?: OgImage | "file";
};

/**
 * Robots directives for a page. Indexable pages allow full-length snippets and
 * large image previews, which is what lets Google AI Overviews and other
 * answer surfaces quote the page at length instead of a truncated line.
 */
export function robotsFor(index = true): Metadata["robots"] {
  if (!isIndexable || !index) {
    return { index: false, follow: isIndexable };
  }

  return {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  };
}

/**
 * Builds the complete metadata for a page: title, description, canonical URL,
 * Open Graph, Twitter card and robots.
 *
 * Next.js merges metadata shallowly, so a page that sets `openGraph` at all
 * replaces the layout's version wholesale. Going through this helper keeps
 * every field present on every page instead of silently dropping siteName,
 * locale or the card type.
 */
export function pageMetadata({
  path,
  title,
  description,
  index = true,
  type = "website",
  image,
}: PageMetadataOptions): Metadata {
  // The home page leads with the brand; every other page leads with its own
  // title and carries the brand as a suffix.
  const fullTitle = path === "/" ? DEFAULT_TITLE : pageTitle(title, siteConfig.name);
  // With "file" the key is left out entirely: even an undefined `images` stops
  // Next.js from applying the route's opengraph-image file. The Twitter card
  // falls back to the Open Graph image on its own.
  const images = image === "file" ? {} : { images: [image ?? DEFAULT_OG_IMAGE] };

  return {
    title: { absolute: fullTitle },
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      url: path,
      title: fullTitle,
      description,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      ...images,
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      site: siteConfig.twitterHandle,
      creator: siteConfig.twitterHandle,
    },
    robots: robotsFor(index),
  };
}
